<a href="https://colab.research.google.com/github/Gabriela2685/Sismos/blob/main/Sismos_7.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [12]:
import pandas as pd

In [13]:
sismos7 = pd.read_csv('https://docs.google.com/spreadsheets/d/e/2PACX-1vQwIELBKwwZD91Ib1_96POm_i8kG9uJhpEoXAfHzZWy4PifaD_0nJv4tMxcARMSqA/pub?output=csv')

In [14]:
sismos7

    Magnitud   Fecha UTC  Hora UTC
0        7.4   1/19/1900   6:33:30
1        7.5   4/19/1902   2:23:00
2        7.7   9/23/1902  20:18:00
3        7.1  12/12/1902  23:10:00
4        7.6   1/14/1903   1:47:36
..       ...         ...       ...
63       7.1   9/19/2017  18:14:39
64       7.2   2/16/2018  23:39:39
65       7.4   6/23/2020  15:29:03
66       7.1    9/8/2021   1:47:46
67       7.7   9/19/2022  18:05:09

[68 rows x 3 columns]

In [15]:
sismos7['fecha_hora'] = pd.to_datetime(sismos7['Fecha UTC'] + ' ' + sismos7['Hora UTC'])

# Calcula los tiempos de interllegada
sismos7['tiempo_interllegada'] = sismos7['fecha_hora'].diff()

# Convierte los tiempos de interllegada a dÃ­as
sismos7['tiempo_interllegada_dias'] = sismos7['tiempo_interllegada'].dt.total_seconds() / (24 * 3600)

# Acumula los tiempos de interllegada
sismos7['tiempo_acumulado'] = sismos7['tiempo_interllegada_dias'].cumsum()

print(sismos7[['fecha_hora', 'tiempo_acumulado']])

            fecha_hora  tiempo_acumulado
0  1900-01-19 06:33:30               NaN
1  1902-04-19 02:23:00        819.826042
2  1902-09-23 20:18:00        977.572569
3  1902-12-12 23:10:00       1057.692014
4  1903-01-14 01:47:36       1089.801458
..                 ...               ...
63 2017-09-19 18:14:39      42977.486910
64 2018-02-16 23:39:39      43127.712604
65 2020-06-23 15:29:03      43985.371910
66 2021-09-08 01:47:46      44426.801574
67 2022-09-19 18:05:09      44803.480313

[68 rows x 2 columns]

In [21]:
tiempo=sismos7.sort_values(by='tiempo_acumulado', ascending=False)

    Magnitud   Fecha UTC  Hora UTC          fecha_hora tiempo_interllegada  \
67       7.7   9/19/2022  18:05:09 2022-09-19 18:05:09   376 days 16:17:23
66       7.1    9/8/2021   1:47:46 2021-09-08 01:47:46   441 days 10:18:43
65       7.4   6/23/2020  15:29:03 2020-06-23 15:29:03   857 days 15:49:24
64       7.2   2/16/2018  23:39:39 2018-02-16 23:39:39   150 days 05:25:00
63       7.1   9/19/2017  18:14:39 2017-09-19 18:14:39    11 days 13:25:22
..       ...         ...       ...                 ...                 ...
4        7.6   1/14/1903   1:47:36 1903-01-14 01:47:36    32 days 02:37:36
3        7.1  12/12/1902  23:10:00 1902-12-12 23:10:00    80 days 02:52:00
2        7.7   9/23/1902  20:18:00 1902-09-23 20:18:00   157 days 17:55:00
1        7.5   4/19/1902   2:23:00 1902-04-19 02:23:00   819 days 19:49:30
0        7.4   1/19/1900   6:33:30 1900-01-19 06:33:30                 NaT

    tiempo_interllegada_dias  tiempo_acumulado
67                376.678738      44803.480313
66                441.429664      44426.801574
65                857.659306      43985.371910
64                150.225694      43127.712604
63                 11.559282      42977.486910
..                       ...               ...
4                  32.109444       1089.801458
3                  80.119444       1057.692014
2                 157.746528        977.572569
1                 819.826042        819.826042
0                        NaN               NaN

[68 rows x 7 columns]

In [24]:
tiempo_acumulado = tiempo['tiempo_acumulado']
tiempo_acumulado

67    44803.480313
66    44426.801574
65    43985.371910
64    43127.712604
63    42977.486910
          ...
4      1089.801458
3      1057.692014
2       977.572569
1       819.826042
0              NaN
Name: tiempo_acumulado, Length: 68, dtype: float64

In [27]:
# Suponiendo que tiempo_acumulado es una serie de Pandas
tiempo_acumulado_lista = tiempo_acumulado.tolist()

[44803.4803125, 44426.80157407408, 43985.37190972223, 43127.71260416667, 42977.486909722225, 42965.92762731482, 41727.32906250001, 41200.41828703704, 40968.47868055556, 40252.671666666676, 37622.81462962964, 36413.41508101853, 35421.579814814824, 35099.85751157408, 34972.83712962964, 34961.37666666668, 34936.31322916668, 34202.52739583334, 31290.79425925927, 31289.280775462972, 30100.992002314822, 29863.86719907408, 29498.347291666672, 28908.19010416667, 28803.555092592596, 27774.102962962967, 26884.136932870373, 26674.602569444447, 25667.31115740741, 25032.314664351856, 23957.550370370373, 23544.03383101852, 22757.31836805556, 21009.087962962967, 18591.32106481482, 18539.402662037042, 16231.05930555556, 15739.116145833337, 15539.710752314819, 15061.52524305556, 14729.918877314818, 13852.280879629632, 13701.884525462965, 13112.647071759262, 12764.508506944447, 11838.151851851853, 11823.169004629632, 11317.803587962964, 10489.852523148149, 10424.496377314816, 10375.86525462963, 10288.905555555557, 7686.075856481482, 5708.782847222223, 5182.755416666667, 4348.528333333334, 4156.186944444445, 3479.1794444444445, 2988.6875, 2826.3498611111113, 2641.9823611111115, 2272.6142361111115, 2157.953819444445, 1089.8014583333336, 1057.692013888889, 977.5725694444445, 819.8260416666667, nan]

In [ ]:
for i in range(len(tiempo_acumulado_lista)):
    tiempo_acumulado_lista[i] =